//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int emp_id { get; set; }
        public string emp_tipid { get; set; }
        public string emp_numid { get; set; }
        public string emp_nom { get; set; }
        public string emp_dir { get; set; }
        public string emp_ciu { get; set; }
        public string emp_depto { get; set; }
        public string emp_tel { get; set; }
        public string emp_tel2 { get; set; }
        public string emp_tel3 { get; set; }
        public string emp_email { get; set; }
        public string emp_web { get; set; }
        public string emp_rlegal { get; set; }
        public Nullable<System.DateTime> emp_fconstit { get; set; }
        public Nullable<System.DateTime> emp_fregistro { get; set; }
    }
}
